version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - yum install -y nginx

  build:
    commands:
      - echo Build started on `date`
      - mkdir -p /var/www/html
      - cp index.html /var/www/html/
      - cp style.css /var/www/html/
      - cp script.js /var/www/html/
      - cp rahul.profile.jpg /var/www/html/
      - echo Files copied to /var/www/html

artifacts:
  files:
    - index.html
    - style.css
    - script.js
    - rahul.profile.jpg
